/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as disperseSol from "./Disperse.sol";
export type { disperseSol };
import type * as disperseGaslessSol from "./DisperseGasless.sol";
export type { disperseGaslessSol };
export type { Token } from "./Token";
