/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Disperse } from "./Disperse";
export type { IERC20 } from "./IERC20";
export * as factories from "./factories";
export { Disperse__factory } from "./factories/Disperse__factory";
export { IERC20__factory } from "./factories/IERC20__factory";
