/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DisperseGaslessV2__factory } from "./DisperseGaslessV2__factory";
export { IERC20__factory } from "./IERC20__factory";
